[package]
name = "mugraph-wallet"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mugraph_wallet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
mugraph-core = { workspace = true }
blake2 = "0.10"
coset = "0.4"
dirs = "6"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
hex = "0.4"
muhex = { workspace = true }
rand = { workspace = true }
rand_core_06 = { package = "rand_core", version = "0.6" }
redb = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
tauri = { version = "2", features = [] }
thiserror = "2"
tauri-plugin-opener = "2"
tokio = { workspace = true }
whisky-csl = "1.0.24"

[dev-dependencies]
tempfile = "3"
