use blake3::Hash;
use ed25519_dalek::{SigningKey, VerifyingKey};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Theta {
    /// The asset ID, generated by hashing the policy_id and the asset_id from the original Cardano
    /// Asset.
    pub asset_id: Hash,
    /// The amount of the asset included inside the theta
    pub amount: u128,
    /// The public key used to verify the spending of this Theta when included in a Delta
    pub public_spend_key: VerifyingKey,
    /// The signing key used to spend this Theta
    pub spend_key: SigningKey,
}

impl Theta {
    pub fn as_bytes(&self) -> Vec<u8> {
        self.asset_id
            .as_bytes()
            .to_vec()
            .iter()
            .chain(&self.amount.to_be_bytes())
            .chain(self.public_spend_key.as_bytes())
            .copied()
            .collect()
    }
}

impl std::hash::Hash for Theta {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.as_bytes().hash(state);
    }
}
